import type {Metadata} from "next";
import "../globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import {Header} from "@/components/header/Header";
import {Children, Renderable} from "@/utilities/ComponentUtilities";

export const metadata: Metadata = {
    title: "CommerceIQ",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: Children;
}>): Renderable {
    return (
        <ClerkProvider dynamic>
            <html lang="en">
                <body>
                <main>
                    <Header />
                    {children}
                </main>
                </body>
            </html>
        </ClerkProvider>
    );
}
